---
title: "assignment"
output: html_document
date: "2026-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
  library(AnnotationHub)
  library(Rsubread)
  library(rtracklayer)
  library(Biostrings)
  library(Rfastp)
  library(epiwraps)
  library(GenomicRanges)
})
ah <- AnnotationHub()
```

## Downloading files
```{r}
genome <- ah[["AH49674"]]
dir.create("BDGP6_genome")
export(import.2bit(genome), "BDGP6_genome/genome.fasta.gz", compress=TRUE)
```

## Building an index
```{r, eval=FALSE}
Rsubread::buildindex("BDGP6_genome/rsubread", reference="BDGP6_genome/genome.fasta.gz")
```

## Alignment
```{r}
dir.create("aligned")
align.stats <- Rsubread::align(index="BDGP6_genome/rsubread",
  type="dna",
  readfile1="raw/ENCFF127RRR.fastq.gz",  
  output_file="aligned/sample.bam",
  nthreads=6, 
  sortReadsByCoordinates=TRUE
)
align.stats
```

## Mapping statistics
```{r}
mapped_reads <- align.stats["Mapped_reads", 1]
total_reads <- align.stats["Total_reads", 1]

mapping_percent <- round(mapped_reads / total_reads * 100, 2)

print(paste("Number of reads:", mapped_reads))
print(paste("Mapping percentage:", mapping_percent))
```



## Peak calling
```{r}
dir.create("peaks")

# if (!require("BiocManager", quietly=TRUE))
#   install.packages("BiocManager")
# 
# BiocManager::install("MACSr")
# 
# MACSr::install_macs3()
# 
# if(!require("MACSr",quietly=TRUE)) BiocManager::install("MACSr")
# 
# library(MACSr)
# 
# callpeak(tfile="aligned/sample.bam", cfile = "aligned/input.bam",
#          gsize="dm", outdir = "peaks", name = "sample")
# 
# peaks <- rtracklayer::import("peaks/sample_peaks.narrowPeak")
# peaks

peaks <- epiwraps::callPeaks(
  bam = "aligned/sample.bam",
  control = "aligned/input.bam"
)
peaks

number_of_peaks <- length(peaks)
print(paste("Number of peaks that are found:", number_of_peaks))
```

## Looking at peaks

```{r}
genes <- ah[["AH49674"]]  

dm <- query(ah, c("Drosophila melanogaster", "EnsDb"))
dm <- ah[[rev(dm$ah_id)[1]]]

dm_genes <- genes(dm)

peaks_in_genes <- findOverlaps(peaks, dm_genes)
peak_of_interest <- queryHits(peaks_in_genes)[1]

peak_of_interest
```

```{r}
dir.create("coverage_tracks")

plotSignalTracks(
  list(CTFC = "aligned/sample.bam", Peaks = peaks),
  region = peaks[peak_of_interest],
  extend = 5000
)
```
## Final report
```{r}
print(paste("Number of reads:", mapped_reads))
print(paste("Mapping percentage:", mapping_percent))
print(paste("Number of peaks that are found:", number_of_peaks))
```

